### ISSUE TITLE
Markbot telling me I need transition (even though I have it in my code)

### ISSUE THREAD

**Issue by digitalsara** [digitalsara/but-em-buttons#1]
@hellachella

Hey Chelle, I think there's a glitch with Markbot. Or I'm missing something. It's telling me that I need a transition (even though in a haste I've added transitions everywhere I have transforms).

Markbot is also perpetually computing. For some reason it never stops computing for this repo.

Any idea why?

<a href="https://ibb.co/kx1Sfb"><img src="https://preview.ibb.co/d0MSfb/Screen_Shot_2017_10_06_at_9_16_08_PM.png" alt="Screen_Shot_2017_10_06_at_9_16_08_PM" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'> </a><br />

**Comment by hellachella** [comment]
Hi Sara, 

This looks like a job for @thomasjbradley

**Comment by thomasjbradley** [comment]
I see the problem, but I also see that Markbot should be a little more descriptive.

In the assignment requirements it says that you need to use the class `.btn-ghost`, which you use in the HTML, but not in the CSS. Markbot is checking for the `transition` on `.btn-ghost`, which it can't find because `.btn-ghost` isn't used in the CSS.

So, adding `.btn-ghost` I think should fix the problem.
And I'll look into why that error message isn't explaining to you that `.btn-ghost` is missing.

**Comment by digitalsara** [comment]
I see, that fixed the issue, thanks so much! Only now it just won't stop computing...

**Comment by thomasjbradley** [comment]
Oh, yeah, I see the permanent spinning—seems stuck on the PNG. I'm looking into why.

**Comment by thomasjbradley** [comment]
Your PNG is not a PNG—it's a JPG with a `.png` extension. I'm making a fix for Markbot but just re-exporting the image properly should solve the problem.

**Comment by digitalsara** [comment]
Ah, that makes sense. Man it's been a while since I've been stuck like this. Now it's telling me that my background colour doesn't change on hover? I've tried targeting `.btn:hover`, `.btn-wrapper a:hover`, `.btn-ghost:hover`, or even just the anchor tag, and all of those succeed at changing the background colour. Am I still missing something?

Again, thank you.

<a href="https://ibb.co/h8Enfb"><img src="https://preview.ibb.co/ndHUtw/Screen_Shot_2017_10_07_at_2_11_49_PM.png" alt="Screen_Shot_2017_10_07_at_2_11_49_PM" border="0"></a>

**Comment by thomasjbradley** [comment]
I think it's the way you set up the HTML. The icon should be inside the `<a>` tag because that's the thing we want to click & hover. The icon is outside the `<a>` tag and positioned over the `<a>` tag preventing the hover from activating sometimes. Move your mouse really slowing up and down in the centre of the button and you see the hover deactivates when it interacts direction with the icon instead.

The `.btn-wrapper` is too powerful, we're not hovering over some random `<div>` we're hovering over the button—the `<a>` tag. `.btn-wrapper` shouldn’t even exist, or at least should have absolutely nothing to do with `:hover`

**Comment by digitalsara** [comment]
Oh, thanks for being so thorough, I get it now! And now Markbot approves. Yay!

Happy Thanksgiving :)
